spring.application.name=filetask

//db접속용
spring.datasource.url=jdbc:postgresql://localhost:5433/filetask
spring.datasource.username=postgres
spring.datasource.password=1111
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
//로그확인용
spring.jpa.show-sql=true
spring.jpa.properties.format_sql=true